Properly parse the Content-Type header
OliverJAsh/express-fp pull request #1
Opened 2018-10-28 20:30 UTC by anttih

The Content-Type can include the charset and boundary parameters which
where not been taking into account. Now it's using the content-type
library to parse it.

2018-10-28 20:30 UTC, anttih commented
Looks like yarn also updated some packages. Hope this is ok.

2018-10-29 08:25 UTC, OliverJAsh requested changes
Thanks for the PR! How are you finding the library? I'm glad it has some users…

Just two minor changes requested, otherwise looks great and makes sense!

2018-10-29 08:25 UTC, OliverJAsh commented on src/index.ts
> +        .mapLeft(error => `Cannot parse Content-Type header: ${error.message}`)
Will `error` always be an object of type `{ message: string }`? If not, what if it's not that type? `error.message` might throw.

Update: I realised we're not handling this elsewhere, so don't worry about it.

2018-10-29 08:25 UTC, OliverJAsh commented on src/index.ts
> +                `Expecting request header '${Header.ContentType}' to equal '${ContentType.ApplicationJson}' but instead got '${ct}'.`,
This error is misleading now, because we don't expect it to equal to `'${ContentType.ApplicationJson}'` exactly. Rather, we expect the MIME type inside the header to equal that. Want to update the messaging to clarify that?

2018-10-29 08:25 UTC, OliverJAsh commented on src/index.ts
> +        .mapLeft(error => `Cannot parse Content-Type header: ${error.message}`)
You can re-use `Header.ContentType` here.

2018-10-29 14:52 UTC, anttih commented
Fixed!

So far I'm just trying it out in a test project. So far so good!

2018-10-29 14:54 UTC, OliverJAsh approved these changes

2018-10-29 14:55 UTC, OliverJAsh commented
I'll merge and release this tonight.

2018-10-31 10:39 UTC, merged

2018-10-31 10:44 UTC, OliverJAsh commented on yarn.lock
> +  version "5.11.0"
Was tslint upgraded for any reason in particular?

2018-10-31 10:44 UTC, OliverJAsh commented
Sorry for the delay! Released as 0.0.15.

2018-10-31 12:50 UTC, anttih commented
No particular reason for the updates. I think I just run `yarn install` and it decided to update the packages.

Thanks!